# S3 연결 설정
cloud:
  aws:
    s3:
      bucket: bangrang-bucket
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIAVB4WTZEVRB6JL6PD
      secret-key: 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
  naver:
    client_id: xivofkt7y5
    client_secret: kNHOAmrLVU2R6N3K3PKDKnHuzSfEoT6vBkQrVCge


spring:
  h2:
    console:
      enabled: false

  # postgis 설정
#  hibernate:
#    dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # jpa 설정
  jpa:
    hibernate:
      ddl-auto: update
#      hibernate:
      dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    use_sql_comments: true
    database: postgresql
#    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect

  # db 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bangrang?charSet=utf-8&prepareThreshold=1
    username: postgres
    password: 1234

  # redis 설정
  data:
    redis:
      host: k9b109.p.ssafy.io
      port: 6379
      password: b109ssafy!

  # 파일 업로드 용량제한
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  # 소셜로그인 세팅
  security:
    oauth2:
      client:
        # kakao는 수정했고 구글 네이버는 나중에
        registration:
          google:
            client-id: 등록해야함
            client-secret: 등록해야함
            scope: profile
            redirect-uri: https://k9b109.p.ssafy.io/login/oauth2/code/google
          naver:
            client-id: 등록해야함
            client-secret: 등록해야함
            client-name: Naver
            authorization-grant-type: authorization_code
            scope: profile_image
            redirect-uri: https://k9b109.p.ssafy.io/login/oauth2/code/naver
          kakao:
            client-id: e523007588cde7cbef9cd8fe7f9e6577
            client-secret: 3pIDmX8IyWNIrQF5iJg0EW9IHgk3uIIf
            client-name: Kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            #            scope: profile_image
            redirect-uri: https://localhost:8080/login/oauth2/code/kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # Spring Batch 설정
  batch:
    job:
      enabled: true
    jdbc:
      # never로 바꿔주기
      initialize-schema: always

# jwt 설정
jwt:
  # 시크릿키 나중에 바꾸자
  secretKey: d2k4lnflak0gsdfmj2nefi053nlgdmgo2i4rio24t60545k45ym32lkrn2l3kj094634n2fjnlsklagihrigkslnvkioi4909028374rfnklskgjmelsmbjxlfajwqbffvzjkdjflapoqwueyr932jnzcxvbmdfjewoihqgfhad9s0t
  access:
    expiration: 3600000
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-Refresh

logging.level:
  org.springframework.data.redis: ERROR

kakao:
  client-id: e523007588cde7cbef9cd8fe7f9e6577
  client-secret: 3pIDmX8IyWNIrQF5iJg0EW9IHgk3uIIf
  #            scope: profile_image
  redirect-uri: https://localhost:8080/login/oauth2/code/kakao


server:
  port: 8081