spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://k9b109.p.ssafy.io:6033/bangrang?createDatabaseIfNotExist=true
#    username: bangrang-b109
#    password:
    url: jdbc:mysql://localhost:3306/bangrang
    username: root
    password: 1234
